server.port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cache-db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    end-point:
      uri: ${NOTIFICATION_QUEUE_URL}

notification:
  sender: "cache.aumenta.tu.valor@gmail.com"
  subject: "Un paso más para empezar a aumentar tu caché!"
  template: d-4dc38c26e21e4208b3efc5390f88d4d4
  url:
    base: ${BASE_URL}
    endpoint: api/v1/confirm/

sendgrid:
  api-key: ${SENDGRID_API_KEY}
  endpoint: mail/send
  sendmail: ${SEND_MAIL}