server.port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cache-db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

cloud:
  aws:
    region:
      static: us-east-1
      # static: eu-west-1
      auto: false
    credentials:
      access-key: AKIASL4IVGME5U3BIOGT
      secret-key: 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
      # access-key: test
      # secret-key: test
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/162958488329/notification-queue
      # uri: http://localhost:4566/000000000000/notification-queue

